services:
  - type: web
    name: rallybot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
    autoDeploy: true 